# fly.toml app configuration file for watchornot-frontend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'watchornot-frontend'
primary_region = 'sjc'

[build]
  [build.args]
    VITE_BACKEND_URL = "https://watchornot-backend.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

# Using TCP health checks instead of HTTP for more reliability
[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  timeout = "10s"
  type = "tcp"
  port = 8080

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
