# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy Web
on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/**'
      - '.github/workflows/fly-deploy-web.yml'
  workflow_dispatch:  # Also allow manual trigger

jobs:
  deploy:
    name: Deploy web app
    runs-on: ubuntu-latest
    concurrency: deploy-web-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy web app to Fly.io
        run: |
          cd packages/web
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
